esphome:
  name: estia-controller
  friendly_name: Estia Controller

esp8266:
  board: d1_mini

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Estia-Controller"
    password: "changeme"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/Etacovda/toshiba_uart_ctrl
      ref: main
    components: [ToshibaUART]
    refresh: 0s

ToshibaUART:
  update_interval: 5s
  id: toshibauart

binary_sensor:
  - platform: ToshibaUART
    pump_onoff:
      name: "Toshiba Pump On/Off"
      id: pump_onoff
    heat_pump_heating:
      name: "Heat Pumping"
    heat_resistor_heating:
      name: "Heating with Coil"
    hotwater_pump_heating:
      name: "Hotwater heat pumping"
    hotwater_resistor_heating:
      name: "Hotwater Coil heating"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: ToshibaUART
    zone1_water_temp:
      name: "Zone 1 Water Temperature"
    outside_air_temp:
      name: "Outdoor Ambient Temperature"
    oudoor_unit_current:
      name: "Outdoor Unit Current"
    heating_compressor_uptime:
      name: "Heating Compressor Uptime"
    inlet_temp:
      name: "Water Inlet Temperature"
    outlet_temp:
      name: "Water Outlet Temperature"
    low_pressure:
      name: "Low Pressure"
    hw_cylinder_temp:
      name: "Hot Water Cylinder Temperature"
    discharge_temp:
      name: "Discharge Temperature"
    suction_temp:
      name: "Suction Temperature"

number:
  - platform: ToshibaUART
    zone1_target_temp:
      name: "Zone 1 Target Temperature"
      mode: box

    hotwater_target_temp:
      name: "Hot Water Target Temperature"
      mode: box

switch:
  - platform: ToshibaUART
    zone1_switch:
      name: "Zone 1 Enable"
    hotwater_switch:
      name: "Hot Water Enable"
    auto_mode_switch:
      name: "Auto Mode"
    cooling_mode_switch:
      name: "Cooling Mode"

uart:
  id: uart_bus
  tx_pin:
    number: D8
  rx_pin:
    number: D7
  baud_rate: 2400
  rx_buffer_size: 2048
  stop_bits: 1
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: true
